// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClMG9e2qZp0yGfUshv1SwYG2ApT0DDNz0',
    appId: '1:223648767420:web:20d032525b6f26267ddfb9',
    messagingSenderId: '223648767420',
    projectId: 'emergency-alert-app-bae0a',
    authDomain: 'emergency-alert-app-bae0a.firebaseapp.com',
    storageBucket: 'emergency-alert-app-bae0a.firebasestorage.app',
    measurementId: 'G-F92DPGKWX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsSC4wf7sUMEvokcAnAp3fBwJxLQwmns',
    appId: '1:223648767420:android:25050611f87134f87ddfb9',
    messagingSenderId: '223648767420',
    projectId: 'emergency-alert-app-bae0a',
    storageBucket: 'emergency-alert-app-bae0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCdX5UfsiBnfbIai02XI48BDYiEfrWkSI',
    appId: '1:223648767420:ios:1336983b2c00c9507ddfb9',
    messagingSenderId: '223648767420',
    projectId: 'emergency-alert-app-bae0a',
    storageBucket: 'emergency-alert-app-bae0a.firebasestorage.app',
    androidClientId: '223648767420-2p14564t5735b4n0iq5oh65q97afq7pp.apps.googleusercontent.com',
    iosClientId: '223648767420-22i2b92j8ltlmkg7d5bh34m7vvicv1ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyAlertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCdX5UfsiBnfbIai02XI48BDYiEfrWkSI',
    appId: '1:223648767420:ios:1336983b2c00c9507ddfb9',
    messagingSenderId: '223648767420',
    projectId: 'emergency-alert-app-bae0a',
    storageBucket: 'emergency-alert-app-bae0a.firebasestorage.app',
    androidClientId: '223648767420-2p14564t5735b4n0iq5oh65q97afq7pp.apps.googleusercontent.com',
    iosClientId: '223648767420-22i2b92j8ltlmkg7d5bh34m7vvicv1ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyAlertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClMG9e2qZp0yGfUshv1SwYG2ApT0DDNz0',
    appId: '1:223648767420:web:7c1381e22c88eb9c7ddfb9',
    messagingSenderId: '223648767420',
    projectId: 'emergency-alert-app-bae0a',
    authDomain: 'emergency-alert-app-bae0a.firebaseapp.com',
    storageBucket: 'emergency-alert-app-bae0a.firebasestorage.app',
    measurementId: 'G-VWZPVPG35Q',
  );

}